#!/usr/bin/python3

import sys
from math import *

def revert(x, xi, xf):
        i = 1
        k = 1
        j = x
        while (k < 4):
                i = 1
                x = j
                while (i < xi):
                        x = x * k * (1000 - x) / 1000
                        i += 1
                while (i <= xf):
                        print("%.2f %.2f" % (k, x))
                        x = x * k * (1000 - x) / 1000
                        i += 1
                k += 0.01
        sys.exit(0)

def normal(x, k):
        for i in range(1, 101):
                print("%i %.2f" % (i, x))
                x = x * k * ((1000 - x) / 1000)

def help():
        print("USAGE.\n"
              "     /106bombyx n [k | i0 i1]\n\n"
              "DESCRIPTION\n"
              "    n       number of first generation individuals\n"
              "    k       growth rate from 1 to 4\n"
              "    i0      initial generation (included)\n"
              "    i1      final generation (included)")
        sys.exit(0)

def is_there_aplha(ac, av):
        for i in range(1, ac):
                try:
                        a = float(av[i])
                except:
                        sys.exit(84)

def is_there_negative(ac, av):
        for i in range(1, ac):
                if (float(av[i]) < 0):
                        sys.exit(84)

def error_handle(ac, av):
        is_there_aplha(ac, av)
        is_there_negative(ac, av)
        return (0)

if __name__ == "__main__":
        av = sys.argv
        ac = len(av)
        if (ac == 2):
                if (av[1] == "-h"):
                        help()
                else:
                        sys.exit(84)
        elif (ac == 3 or ac == 4):
                if (error_handle(ac, av) == 84):
                        sys.exit(84)
                elif (ac == 3):
                        if (float(av[2]) < 1 or float(av[2]) > 4):
                                sys.exit(84)
                        normal(float(av[1]), float(av[2]))
                else:
                        if (float(av[2]) > float(av[3])):
                                sys.exit(84)
                        revert(float(av[1]), float(av[2]), float(av[3]))
        else:
                sys.exit(84)
